name: 'dart_snake'
version: 0.0.4
description: The classic Snake game as a Dart web app.

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  build_runner: ^1.10.13
  build_web_compilers: ^2.16.0
